# Generated by Django 5.1.6 on 2025-03-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/default_img.jpg', null=True, upload_to='events_asset'),
        ),
    ]
